-- AlterTable
ALTER TABLE "User" ADD COLUMN "apiUsageCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lastResetDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "proExpiresAt" TIMESTAMP(3);
